# Generated by Django 3.1.1 on 2020-11-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bascket',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
