# Generated by Django 3.1.1 on 2020-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cross_section',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
