# Generated by Django 3.1.1 on 2020-11-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20201106_1254'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bascket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.customer')),
                ('items', models.ManyToManyField(to='cart.CartItem')),
            ],
        ),
    ]
