# Generated by Django 3.1.1 on 2020-11-07 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20201106_1254'),
        ('catalog', '0001_initial'),
        ('cart', '0003_auto_20201106_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.customer'),
        ),
    ]
