# Generated by Django 3.1.1 on 2020-11-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201113_1918'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table=None,
        ),
    ]
