# Generated by Django 3.1.1 on 2020-11-24 03:09

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0008_auto_20201121_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('postal_code', models.IntegerField(validators=[utils.validators.validate_postal_code])),
                ('lat', models.DecimalField(decimal_places=3, max_digits=16)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=16)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.basket')),
            ],
        ),
    ]
