# Generated by Django 3.1.1 on 2020-11-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transport',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
